---
- name: create config dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fish/functions"
    mode: "0755"
    state: directory

- name: configure fish
  ansible.builtin.template:
    src: templates/config.fish.j2
    mode: "0644"
    dest: "{{ __fish_directory }}/config.fish"

- name: creating function definitions
  ansible.builtin.template:
    src: templates/fish_function.j2
    mode: "0644"
    dest: "{{ __fish_directory }}/functions/{{ item.name }}.fish"
  with_items: "{{ fish_functions }}"

- name: creating conf.d definitions
  ansible.builtin.template:
    src: templates/fish_function.j2
    mode: "0644"
    dest: "{{ __fish_directory }}/conf.d/{{ item.name }}.{{ item.extension | default('fish') }}"
  with_items: "{{ fish_confd }}"
